# Generated by Django 5.0.7 on 2024-08-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='referral_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
