# Generated by Django 5.0.7 on 2024-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
