# Generated by Django 5.0.7 on 2024-08-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ewallet_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transactions',
            name='order',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.order'),
            preserve_default=False,
        ),
    ]
