# Generated by Django 5.0.7 on 2024-08-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_brand_product_category_product_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
