# Generated by Django 5.0.7 on 2024-09-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_orderdetail_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
