# Generated by Django 5.0.7 on 2024-09-06 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_category_remove_product_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_purchase', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.user')),
            ],
        ),
    ]
