# Generated by Django 5.0.7 on 2024-09-06 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_monthlypurchase_statements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypurchase',
            name='month',
        ),
        migrations.AddField(
            model_name='monthlypurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
