# Generated by Django 5.0.7 on 2024-09-06 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_monthlypurchase_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypurchase',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlypurchase',
            name='referral_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypurchase',
            name='user_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
