# Generated by Django 5.0.7 on 2024-09-11 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_category_image_url_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypurchase',
            name='cumulative_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlypurchase',
            name='cumulative_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlypurchase',
            name='group_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlypurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_purchase', to='api.user'),
        ),
        migrations.CreateModel(
            name='CommissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cumulative_purchase', models.PositiveIntegerField(default=0)),
                ('cumulative_points', models.PositiveIntegerField(default=0)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_history', to='api.user')),
            ],
        ),
    ]
