# Generated by Django 5.0.7 on 2024-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_monthlypurchase_cumulative_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionhistory',
            name='order_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionhistory',
            name='referral_total_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionhistory',
            name='user_total_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
