# Generated by Django 5.0.7 on 2024-09-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_commissionhistory_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypurchase',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
