# Generated by Django 5.0.7 on 2024-09-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_monthlypurchase_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout_transaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
